POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/1176d54b-ef94-4259-89ba-f494380ae397/attendees
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego2@rocketseat.com.br"
}

###

GET http://localhost:3333/events/1176d54b-ef94-4259-89ba-f494380ae397

###

GET http://localhost:3333/attendees/2/badge

###
