POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Startup Summit",
  "details": "O melhor evento de startups da América Latina",
  "maximumAttendees": 200
}

###

POST http://localhost:3333/events/96debd8c-c19f-4f1c-8ff9-7ceadbbf83a5/attendees
Content-Type: application/json

{
  "name": "Bárbara Marcheti Fiorin",
  "email": "bmarchetifiorin@gmail.com"
}

###

GET http://localhost:3333/events/96debd8c-c19f-4f1c-8ff9-7ceadbbf83a5

###

GET http://localhost:3333/attendees/10070/badge

###

GET http://localhost:3333/attendees/10121/check-in

###

GET http://localhost:3333/events/96debd8c-c19f-4f1c-8ff9-7ceadbbf83a5/attendees

###

GET http://localhost:3333/events/96debd8c-c19f-4f1c-8ff9-7ceadbbf83a5/attendees?query=diego
